version: "3.8"

services:
  backend:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: alllec_backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./BackEnd:/app
      - /app/node_modules 
      - ./BackEnd/sqlite_data:/app/sqlite_data
    env_file:
      - .env


  frontend:
    build: 
      context: ./FrontEnd
    container_name: alllec_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
